### ISSUE TITLE
New fork for MCUFriends-Display

### ISSUE THREAD

**Issue by adebaumann** [mjculross/Enigma_Visual_Simulator#1]
Hi Mark,

...not an issue as such, just a heads up that I've forked your excellent project and adapted it to run on HX8347-Displays with Non-SPI touchscreen interfaces. It seems that due to less optimization of the libraries, users will have to choose between the crinkle-paint-background or the serial interface - both together push the code to 101%...

Thanks!
Ade

**Comment by mjculross** [comment]
Adrian:
Thanks for the heads-up on the fork.  As you've experienced, whenever either the libraries are updated or the IDE is updated, I cringe to see if the code once again exceeds the available space.  Unfortunately, right now we're suffering from that condition where we can't have all of the functionality at the same time & still fit within code space !!
Good luck with your new display . . .
Mark J CulrossKD5RXT

    On Monday, June 24, 2019, 9:47:20 AM CDT, Adrian A. Baumann <notifications@github.com> wrote:  
 
 
Hi Mark,

...not an issue as such, just a heads up that I've forked your excellent project and adapted it to run on HX8347-Displays with Non-SPI touchscreen interfaces. It seems that due to less optimization of the libraries, users will have to choose between the crinkle-paint-background or the serial interface - both together push the code to 101%...

Thanks!
Ade

**Comment by sammy966** [comment]
HI, I have problems with the calibration because my screen works with the library MCUFRIEND_kbv therefore the code, even if it works correctly, is not seen well on my screen. Would you have any advice on how to make it work?
My problem is that although the code works on my screen but it is not seen in full screen as seen in the picture.
![IMG_20200510_152808](https://user-images.githubusercontent.com/65167182/81558921-d10ab380-938e-11ea-9676-ccb2c6e32d2a.jpg)

Thanks in advance

**Comment by mjculross** [comment]
Try increasing the size of the font that you use & see if you can find one that causes the text to make use of the entire screen.
