### ISSUE TITLE
Enigma Visual (Not enough Storage)

### ISSUE THREAD

**Issue by ksloc096** [mjculross/Enigma_Visual_Simulator#2]
Hey, I am currently having some problems with uploading the EnigmaVisuals.ino file into my Arduino and the reason why it could not work is that my maximum size for my Arduino device is 32256 while the sketch uses 32916. Does anyone know how to shorten the code so I can still upload it on my Arduino UNO?

**Comment by mjculross** [comment]
As a start, I would suggest to follow the instructions at the top of the source file for disabling the serial interface.
Mark J CulrossKD5RXT

Sent from AT&T Yahoo Mail on Android 
 
  On Sat, Sep 25, 2021 at 1:00 AM, ***@***.***> wrote:   


Hey, I am currently having some problems with uploading the EnigmaVisuals.ino file into my Arduino and the reason why it could not work is that my maximum size for my Arduino device is 32256 while the sketch uses 32916. Does anyone know how to shorten the code so I can still upload it on my Arduino UNO?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ksloc096** [comment]
Hey so I actually notice the problem and that is placing two programs in
one sketch. So I uploaded one of the program (ie TFTCal) and it worked. Now
I have followed your suggestion and imported the library files that are
necessary to run the EnigmaVisual program and my current problem is that I
do not have enough storage or space for my Arduino to store the
EnigmaVisual program. My question is, is there a way to shorten the
EnigmaVisual program so that I can possibly upload it?

The maximum storage I can upload for my Arduino Uno is 32256 bytes and the
sketch uses 32916 bytes.

**Comment by mjculross** [comment]
Once again, I would suggest to follow the instructions for disabling the serial interface (you can find the instructions both at the top of the source file & in the body of the README file).
 Mark J Culross
KD5RXT

**Comment by mjculross** [comment]
The solution to this "issue" is clearly addressed, both in the README file & in the INO source file.  Unfortunately, we are at the mercy of the library maintainers to do a good job of creating efficient (as small as possible) libraries.

**Comment by ksloc096** [comment]
Oh uhh Sorry Mark I got it all resolved. Sorry for not letting you know.


Best

Kent

**Comment by ksloc096** [comment]
Oh and thank you for your time in helping me!
